apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/facuxfdz/response-time-app-infra.git
    targetRevision: HEAD
    path: dev/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true